<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Spatie\Permission\Models\Role;
use Spatie\Permission\Models\Permission;

class ComprehensivePermissionsSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // Reset cached roles and permissions
        app()[\Spatie\Permission\PermissionRegistrar::class]->forgetCachedPermissions();

        // Define permissions based on actual system routes and functionality
        $permissions = [
            // 📊 إدارة المبيعات (Sales Management) - Based on actual routes
            'sales.dashboard.view' => 'عرض لوحة تحكم المبيعات',
            'sales.orders.view' => 'عرض طلبات المبيعات',
            'sales.orders.create' => 'إنشاء طلبات المبيعات',
            'sales.orders.edit' => 'تعديل طلبات المبيعات',
            'sales.orders.delete' => 'حذف طلبات المبيعات',
            'sales.invoices.view' => 'عرض الفواتير',
            'sales.invoices.create' => 'إنشاء الفواتير',
            'sales.invoices.edit' => 'تعديل الفواتير',
            'sales.invoices.delete' => 'حذف الفواتير',
            'sales.invoices.print' => 'طباعة الفواتير',
            'sales.invoices.send-email' => 'إرسال الفواتير بالبريد الإلكتروني',
            'sales.customers.view' => 'عرض العملاء',
            'sales.customers.create' => 'إضافة عملاء جدد',
            'sales.customers.edit' => 'تعديل بيانات العملاء',
            'sales.customers.delete' => 'حذف العملاء',
            'sales.customers.import' => 'استيراد العملاء',
            'sales.customers.export' => 'تصدير العملاء',
            'sales.products.view' => 'عرض المنتجات',
            'sales.products.create' => 'إضافة منتجات جديدة',
            'sales.products.edit' => 'تعديل المنتجات',
            'sales.products.delete' => 'حذف المنتجات',
            'sales.products.import' => 'استيراد المنتجات',
            'sales.products.export' => 'تصدير المنتجات',
            'sales.returns.view' => 'عرض المرتجعات',
            'sales.returns.create' => 'إنشاء مرتجعات',
            'sales.returns.edit' => 'تعديل المرتجعات',
            'sales.returns.complete' => 'إكمال المرتجعات',
            'sales.returns.reject' => 'رفض المرتجعات',
            'sales.targets.view' => 'عرض أهداف المبيعات',
            'sales.targets.create' => 'إنشاء أهداف المبيعات',
            'sales.targets.edit' => 'تعديل أهداف المبيعات',
            'sales.targets.delete' => 'حذف أهداف المبيعات',

            // 📦 إدارة المخزون (Inventory Management) - Based on actual routes
            'inventory.view' => 'عرض المخزون الرئيسي',
            'inventory.create' => 'إنشاء عناصر مخزون',
            'inventory.edit' => 'تعديل عناصر المخزون',
            'inventory.delete' => 'حذف عناصر المخزون',
            'inventory.warehouses.view' => 'عرض المستودعات',
            'inventory.warehouses.create' => 'إنشاء مستودعات',
            'inventory.warehouses.edit' => 'تعديل المستودعات',
            'inventory.warehouses.delete' => 'حذف المستودعات',
            'inventory.warehouses.capacity-report' => 'تقرير سعة المستودعات',
            'inventory.warehouses.inventory-report' => 'تقرير مخزون المستودعات',
            'inventory.movements.view' => 'عرض حركات المخزون',
            'inventory.movements.create' => 'إنشاء حركات مخزون',
            'inventory.movements.edit' => 'تعديل حركات المخزون',
            'inventory.movements.delete' => 'حذف حركات المخزون',
            'inventory.audits.view' => 'عرض مراجعات المخزون',
            'inventory.audits.create' => 'إنشاء مراجعات مخزون',
            'inventory.audits.edit' => 'تعديل مراجعات المخزون',
            'inventory.audits.delete' => 'حذف مراجعات المخزون',
            'inventory.adjustments.view' => 'عرض تسويات المخزون',
            'inventory.adjustments.create' => 'إنشاء تسويات مخزون',
            'inventory.adjustments.edit' => 'تعديل تسويات المخزون',
            'inventory.adjustments.delete' => 'حذف تسويات المخزون',
            'inventory.reports.view' => 'عرض تقارير المخزون',

            // 💰 النظام المحاسبي (Accounting System) - Based on actual routes
            'accounting.dashboard.view' => 'عرض لوحة تحكم المحاسبة',
            'accounting.analytics.view' => 'عرض تحليلات المحاسبة',
            'accounting.chart-of-accounts.view' => 'عرض دليل الحسابات',
            'accounting.chart-of-accounts.create' => 'إنشاء حسابات جديدة',
            'accounting.chart-of-accounts.edit' => 'تعديل الحسابات',
            'accounting.chart-of-accounts.delete' => 'حذف الحسابات',
            'accounting.cost-centers.view' => 'عرض مراكز التكلفة',
            'accounting.cost-centers.create' => 'إنشاء مراكز تكلفة',
            'accounting.cost-centers.edit' => 'تعديل مراكز التكلفة',
            'accounting.cost-centers.delete' => 'حذف مراكز التكلفة',
            'accounting.journal-entries.view' => 'عرض القيود المحاسبية',
            'accounting.journal-entries.create' => 'إنشاء قيود محاسبية',
            'accounting.journal-entries.edit' => 'تعديل القيود المحاسبية',
            'accounting.journal-entries.delete' => 'حذف القيود المحاسبية',
            'accounting.journal-entries.post' => 'ترحيل القيود المحاسبية',
            'accounting.journal-entries.reverse' => 'عكس القيود المحاسبية',
            'accounting.reports.trial-balance' => 'عرض ميزان المراجعة',
            'accounting.reports.income-statement' => 'عرض قائمة الدخل',
            'accounting.reports.balance-sheet' => 'عرض الميزانية العمومية',
            'accounting.reports.cash-flow' => 'عرض قائمة التدفقات النقدية',
            'accounting.reports.general-ledger' => 'عرض دفتر الأستاذ العام',
            'accounting.reports.subsidiary-ledger' => 'عرض دفاتر الأستاذ المساعدة',
            'accounting.settings.view' => 'عرض إعدادات المحاسبة',
            'accounting.settings.fiscal-year' => 'إدارة السنة المالية',
            'accounting.settings.currencies' => 'إدارة العملات',
            'accounting.settings.account-numbering' => 'إدارة ترقيم الحسابات',

            // 👥 الموارد البشرية (Human Resources) - Based on actual routes
            'hr.dashboard.view' => 'عرض لوحة تحكم الموارد البشرية',
            'hr.employees.view' => 'عرض الموظفين',
            'hr.employees.create' => 'إضافة موظفين جدد',
            'hr.employees.edit' => 'تعديل بيانات الموظفين',
            'hr.employees.delete' => 'حذف الموظفين',
            'hr.employees.export' => 'تصدير بيانات الموظفين',
            'hr.employees.import' => 'استيراد بيانات الموظفين',
            'hr.departments.view' => 'عرض الأقسام',
            'hr.departments.create' => 'إنشاء أقسام جديدة',
            'hr.departments.edit' => 'تعديل الأقسام',
            'hr.departments.delete' => 'حذف الأقسام',
            'hr.departments.reports' => 'تقارير الأقسام',
            'hr.positions.view' => 'عرض المناصب',
            'hr.positions.create' => 'إنشاء مناصب جديدة',
            'hr.positions.edit' => 'تعديل المناصب',
            'hr.positions.delete' => 'حذف المناصب',
            'hr.positions.reports' => 'تقارير المناصب',
            'hr.attendance.view' => 'عرض الحضور والانصراف',
            'hr.attendance.create' => 'تسجيل الحضور والانصراف',
            'hr.attendance.edit' => 'تعديل الحضور والانصراف',
            'hr.attendance.delete' => 'حذف سجلات الحضور',
            'hr.attendance.reports' => 'تقارير الحضور',
            'hr.leaves.view' => 'عرض الإجازات',
            'hr.leaves.create' => 'إنشاء طلبات إجازة',
            'hr.leaves.edit' => 'تعديل طلبات الإجازة',
            'hr.leaves.delete' => 'حذف طلبات الإجازة',
            'hr.leaves.approve' => 'اعتماد الإجازات',
            'hr.leaves.reject' => 'رفض الإجازات',
            'hr.leave-types.view' => 'عرض أنواع الإجازات',
            'hr.leave-types.create' => 'إنشاء أنواع إجازات',
            'hr.leave-types.edit' => 'تعديل أنواع الإجازات',
            'hr.leave-types.delete' => 'حذف أنواع الإجازات',
            'hr.payroll.view' => 'عرض كشوف الرواتب',
            'hr.payroll.create' => 'إنشاء كشوف رواتب',
            'hr.payroll.edit' => 'تعديل كشوف الرواتب',
            'hr.payroll.delete' => 'حذف كشوف الرواتب',
            'hr.payroll.process' => 'معالجة الرواتب',
            'hr.payroll.approve' => 'اعتماد كشوف الرواتب',
            'hr.shifts.view' => 'عرض الورديات',
            'hr.shifts.create' => 'إنشاء ورديات',
            'hr.shifts.edit' => 'تعديل الورديات',
            'hr.shifts.delete' => 'حذف الورديات',
            'hr.overtime.view' => 'عرض الساعات الإضافية',
            'hr.overtime.create' => 'إنشاء ساعات إضافية',
            'hr.overtime.edit' => 'تعديل الساعات الإضافية',
            'hr.overtime.delete' => 'حذف الساعات الإضافية',
            'hr.overtime.approve' => 'اعتماد الساعات الإضافية',
            'hr.reports.attendance' => 'تقارير الحضور',
            'hr.reports.payroll' => 'تقارير الرواتب',
            'hr.reports.leaves' => 'تقارير الإجازات',
            'hr.reports.overtime' => 'تقارير الساعات الإضافية',
            'hr.reports.employee-summary' => 'تقارير ملخص الموظفين',

            // 🚚 إدارة المشتريات (Procurement Management) - Based on actual routes
            'purchasing.dashboard.view' => 'عرض لوحة تحكم المشتريات',
            'purchasing.suppliers.view' => 'عرض الموردين',
            'purchasing.suppliers.create' => 'إضافة موردين جدد',
            'purchasing.suppliers.edit' => 'تعديل بيانات الموردين',
            'purchasing.suppliers.delete' => 'حذف الموردين',
            'purchasing.suppliers.import' => 'استيراد الموردين',
            'purchasing.suppliers.export' => 'تصدير الموردين',
            'purchasing.purchase-requests.view' => 'عرض طلبات الشراء',
            'purchasing.purchase-requests.create' => 'إنشاء طلبات شراء',
            'purchasing.purchase-requests.edit' => 'تعديل طلبات الشراء',
            'purchasing.purchase-requests.delete' => 'حذف طلبات الشراء',
            'purchasing.purchase-requests.approve' => 'اعتماد طلبات الشراء',
            'purchasing.purchase-orders.view' => 'عرض أوامر الشراء',
            'purchasing.purchase-orders.create' => 'إنشاء أوامر شراء',
            'purchasing.purchase-orders.edit' => 'تعديل أوامر الشراء',
            'purchasing.purchase-orders.delete' => 'حذف أوامر الشراء',
            'purchasing.purchase-orders.approve' => 'اعتماد أوامر الشراء',
            'purchasing.quotations.view' => 'عرض عروض الأسعار',
            'purchasing.quotations.create' => 'إنشاء عروض أسعار',
            'purchasing.quotations.edit' => 'تعديل عروض الأسعار',
            'purchasing.quotations.delete' => 'حذف عروض الأسعار',
            'purchasing.supplier-contracts.view' => 'عرض عقود الموردين',
            'purchasing.supplier-contracts.create' => 'إنشاء عقود موردين',
            'purchasing.supplier-contracts.edit' => 'تعديل عقود الموردين',
            'purchasing.supplier-contracts.delete' => 'حذف عقود الموردين',

            // 🛡️ الشؤون التنظيمية (Regulatory Affairs) - Based on actual routes
            'regulatory.dashboard.view' => 'عرض لوحة تحكم الشؤون التنظيمية',
            'regulatory.companies.view' => 'عرض الشركات المسجلة',
            'regulatory.companies.create' => 'تسجيل شركات جديدة',
            'regulatory.companies.edit' => 'تعديل بيانات الشركات',
            'regulatory.companies.delete' => 'حذف الشركات',
            'regulatory.companies.export' => 'تصدير بيانات الشركات',
            'regulatory.companies.import' => 'استيراد بيانات الشركات',
            'regulatory.inspections.view' => 'عرض التفتيشات',
            'regulatory.inspections.create' => 'إنشاء تفتيشات',
            'regulatory.inspections.edit' => 'تعديل التفتيشات',
            'regulatory.inspections.delete' => 'حذف التفتيشات',
            'regulatory.inspections.export' => 'تصدير التفتيشات',
            'regulatory.inspections.import' => 'استيراد التفتيشات',
            'regulatory.quality-certificates.view' => 'عرض شهادات الجودة',
            'regulatory.quality-certificates.create' => 'إنشاء شهادات جودة',
            'regulatory.quality-certificates.edit' => 'تعديل شهادات الجودة',
            'regulatory.quality-certificates.delete' => 'حذف شهادات الجودة',
            'regulatory.quality-certificates.export' => 'تصدير شهادات الجودة',
            'regulatory.quality-certificates.import' => 'استيراد شهادات الجودة',
            'regulatory.product-recalls.view' => 'عرض سحب المنتجات',
            'regulatory.product-recalls.create' => 'إنشاء سحب منتجات',
            'regulatory.product-recalls.edit' => 'تعديل سحب المنتجات',
            'regulatory.product-recalls.delete' => 'حذف سحب المنتجات',
            'regulatory.product-recalls.export' => 'تصدير سحب المنتجات',
            'regulatory.product-recalls.import' => 'استيراد سحب المنتجات',
            'regulatory.regulatory-reports.view' => 'عرض التقارير التنظيمية',
            'regulatory.regulatory-reports.create' => 'إنشاء تقارير تنظيمية',
            'regulatory.regulatory-reports.edit' => 'تعديل التقارير التنظيمية',
            'regulatory.regulatory-reports.delete' => 'حذف التقارير التنظيمية',
            'regulatory.regulatory-reports.export' => 'تصدير التقارير التنظيمية',
            'regulatory.regulatory-reports.import' => 'استيراد التقارير التنظيمية',

            // 📊 التحليلات والذكاء الاصطناعي (Analytics & AI) - Based on actual routes
            'analytics.dashboard.view' => 'عرض لوحة تحكم التحليلات',
            'analytics.sales.view' => 'عرض تحليلات المبيعات',
            'analytics.financial.view' => 'عرض التحليلات المالية',
            'analytics.inventory.view' => 'عرض تحليلات المخزون',
            'analytics.customers.view' => 'عرض تحليلات العملاء',
            'analytics.products.view' => 'عرض تحليلات المنتجات',
            'analytics.reports.view' => 'عرض التقارير التحليلية',
            'analytics.reports.export' => 'تصدير التقارير التحليلية',

            // 📚 دليل النظام (System Guide) - Based on actual routes
            'system-guide.view' => 'عرض دليل النظام',
            'system-guide.introduction.view' => 'عرض مقدمة النظام',
            'system-guide.modules.view' => 'عرض أدلة الوحدات',
            'system-guide.videos.view' => 'عرض الفيديوهات التعليمية',
            'system-guide.faq.view' => 'عرض الأسئلة الشائعة',
            'system-guide.download-manual' => 'تحميل دليل المستخدم',
            'system-guide.new-tenant-guide.view' => 'عرض دليل المستأجر الجديد',
            'system-guide.start-tour' => 'بدء جولة النظام',

            // 📊 التقارير الديناميكية (Dynamic Reports) - Based on actual routes
            'reports.dashboard.view' => 'عرض لوحة تحكم التقارير',
            'reports.sales.view' => 'عرض تقارير المبيعات',
            'reports.customers.view' => 'عرض تقارير العملاء',
            'reports.products.view' => 'عرض تقارير المنتجات',
            'reports.inventory.view' => 'عرض تقارير المخزون',
            'reports.financial.view' => 'عرض التقارير المالية',
            'reports.hr.view' => 'عرض تقارير الموارد البشرية',
            'reports.purchasing.view' => 'عرض تقارير المشتريات',
            'reports.regulatory.view' => 'عرض التقارير التنظيمية',
            'reports.custom.create' => 'إنشاء تقارير مخصصة',
            'reports.custom.edit' => 'تعديل التقارير المخصصة',
            'reports.export.excel' => 'تصدير التقارير إلى Excel',
            'reports.export.pdf' => 'تصدير التقارير إلى PDF',
            'reports.schedule' => 'جدولة التقارير',
            'reports.email' => 'إرسال التقارير بالبريد الإلكتروني',

            // ⚙️ إدارة النظام (System Management) - Based on actual routes
            'roles.view' => 'عرض الأدوار',
            'roles.create' => 'إنشاء أدوار جديدة',
            'roles.edit' => 'تعديل الأدوار',
            'roles.delete' => 'حذف الأدوار',
            'roles.assign' => 'تعيين الأدوار للمستخدمين',
            'permissions.view' => 'عرض الصلاحيات',
            'permissions.assign' => 'تعيين الصلاحيات',
            'users.view' => 'عرض المستخدمين',
            'users.create' => 'إنشاء مستخدمين جدد',
            'users.edit' => 'تعديل المستخدمين',
            'users.delete' => 'حذف المستخدمين',
            'users.details' => 'عرض تفاصيل المستخدمين',
            'settings.view' => 'عرض إعدادات النظام',
            'settings.edit' => 'تعديل إعدادات النظام',
            'settings.company' => 'إعدادات الشركة',
            'settings.system' => 'إعدادات النظام العامة',
            'settings.notifications' => 'إعدادات الإشعارات',
            'settings.backup' => 'إعدادات النسخ الاحتياطية',
            'dashboard.tenant.view' => 'عرض لوحة تحكم المستأجر',
            'dashboard.admin.view' => 'عرض لوحة تحكم المدير',

            // 🎯 أهداف المبيعات (Sales Targets) - Based on actual routes
            'sales-targets.view' => 'عرض أهداف المبيعات',
            'sales-targets.create' => 'إنشاء أهداف مبيعات',
            'sales-targets.edit' => 'تعديل أهداف المبيعات',
            'sales-targets.delete' => 'حذف أهداف المبيعات',
            'sales-targets.reports' => 'تقارير أهداف المبيعات',

            // 🌍 التوطين والإعدادات المحلية (Localization)
            'localization.currency.manage' => 'إدارة العملة العراقية',
            'localization.tax.manage' => 'إدارة النظام الضريبي العراقي',
            'localization.government-reports.view' => 'عرض التقارير الحكومية',
            'localization.government-reports.generate' => 'إنتاج التقارير الحكومية',
            'localization.banks.manage' => 'إدارة البنوك العراقية',
            'localization.legal.view' => 'عرض المتطلبات القانونية',
        ];

        // Create permissions
        foreach ($permissions as $name => $description) {
            Permission::firstOrCreate(
                ['name' => $name, 'guard_name' => 'web'],
                ['description' => $description]
            );
        }

        $this->command->info('تم إنشاء ' . count($permissions) . ' صلاحية شاملة بنجاح!');
    }
}
