<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Spatie\Permission\Models\Permission;

class ComprehensivePermissionsSeeder extends Seeder
{
    public function run()
    {
        $permissions = [
            // ===== إدارة النظام العامة =====
            'view_dashboard' => 'عرض لوحة التحكم',
            'view_system_settings' => 'عرض إعدادات النظام',
            'edit_system_settings' => 'تعديل إعدادات النظام',
            'backup_system' => 'نسخ احتياطي للنظام',
            'restore_system' => 'استعادة النظام',
            
            // ===== إدارة المستخدمين والأدوار =====
            'view_users' => 'عرض المستخدمين',
            'create_users' => 'إضافة مستخدمين',
            'edit_users' => 'تعديل المستخدمين',
            'delete_users' => 'حذف المستخدمين',
            'activate_users' => 'تفعيل المستخدمين',
            'deactivate_users' => 'إلغاء تفعيل المستخدمين',
            'view_roles' => 'عرض الأدوار',
            'create_roles' => 'إنشاء أدوار',
            'edit_roles' => 'تعديل الأدوار',
            'delete_roles' => 'حذف الأدوار',
            'assign_roles' => 'تعيين الأدوار',
            'view_permissions' => 'عرض الصلاحيات',
            'assign_permissions' => 'تعيين الصلاحيات',
            
            // ===== إدارة المبيعات =====
            'view_sales_dashboard' => 'عرض لوحة تحكم المبيعات',
            'view_customers' => 'عرض العملاء',
            'create_customers' => 'إضافة عملاء',
            'edit_customers' => 'تعديل العملاء',
            'delete_customers' => 'حذف العملاء',
            'import_customers' => 'استيراد العملاء',
            'export_customers' => 'تصدير العملاء',
            'view_customer_details' => 'عرض تفاصيل العملاء',
            'view_sales_orders' => 'عرض طلبات المبيعات',
            'create_sales_orders' => 'إنشاء طلبات المبيعات',
            'edit_sales_orders' => 'تعديل طلبات المبيعات',
            'delete_sales_orders' => 'حذف طلبات المبيعات',
            'approve_sales_orders' => 'الموافقة على طلبات المبيعات',
            'cancel_sales_orders' => 'إلغاء طلبات المبيعات',
            'view_invoices' => 'عرض الفواتير',
            'create_invoices' => 'إنشاء فواتير',
            'edit_invoices' => 'تعديل الفواتير',
            'delete_invoices' => 'حذف الفواتير',
            'print_invoices' => 'طباعة الفواتير',
            'send_invoices' => 'إرسال الفواتير',
            'cancel_invoices' => 'إلغاء الفواتير',
            'view_invoice_qr' => 'عرض QR كود الفواتير',
            'view_returns' => 'عرض المرتجعات',
            'create_returns' => 'إنشاء مرتجعات',
            'process_returns' => 'معالجة المرتجعات',
            'approve_returns' => 'الموافقة على المرتجعات',
            'view_sales_targets' => 'عرض أهداف المبيعات',
            'create_sales_targets' => 'إنشاء أهداف المبيعات',
            'edit_sales_targets' => 'تعديل أهداف المبيعات',
            'delete_sales_targets' => 'حذف أهداف المبيعات',
            'view_sales_performance' => 'عرض أداء المبيعات',
            'view_sales_reports' => 'عرض تقارير المبيعات',
            'export_sales_reports' => 'تصدير تقارير المبيعات',
            
            // ===== إدارة المخزون =====
            'view_inventory_dashboard' => 'عرض لوحة تحكم المخزون',
            'view_products' => 'عرض المنتجات',
            'create_products' => 'إضافة منتجات',
            'edit_products' => 'تعديل المنتجات',
            'delete_products' => 'حذف المنتجات',
            'import_products' => 'استيراد المنتجات',
            'export_products' => 'تصدير المنتجات',
            'view_product_details' => 'عرض تفاصيل المنتجات',
            'manage_product_images' => 'إدارة صور المنتجات',
            'view_categories' => 'عرض فئات المنتجات',
            'create_categories' => 'إنشاء فئات المنتجات',
            'edit_categories' => 'تعديل فئات المنتجات',
            'delete_categories' => 'حذف فئات المنتجات',
            'view_warehouses' => 'عرض المستودعات',
            'create_warehouses' => 'إنشاء مستودعات',
            'edit_warehouses' => 'تعديل المستودعات',
            'delete_warehouses' => 'حذف المستودعات',
            'view_inventory_movements' => 'عرض حركات المخزون',
            'create_inventory_movements' => 'إنشاء حركات المخزون',
            'edit_inventory_movements' => 'تعديل حركات المخزون',
            'delete_inventory_movements' => 'حذف حركات المخزون',
            'view_stock_levels' => 'عرض مستويات المخزون',
            'adjust_stock_levels' => 'تعديل مستويات المخزون',
            'view_low_stock_alerts' => 'عرض تنبيهات المخزون المنخفض',
            'view_inventory_reports' => 'عرض تقارير المخزون',
            'export_inventory_reports' => 'تصدير تقارير المخزون',
            'conduct_stock_count' => 'إجراء جرد المخزون',
            'approve_stock_adjustments' => 'الموافقة على تعديلات المخزون',
            
            // ===== النظام المحاسبي =====
            'view_accounting_dashboard' => 'عرض لوحة تحكم المحاسبة',
            'view_chart_of_accounts' => 'عرض دليل الحسابات',
            'create_accounts' => 'إنشاء حسابات',
            'edit_accounts' => 'تعديل الحسابات',
            'delete_accounts' => 'حذف الحسابات',
            'view_journal_entries' => 'عرض القيود المحاسبية',
            'create_journal_entries' => 'إنشاء قيود محاسبية',
            'edit_journal_entries' => 'تعديل القيود المحاسبية',
            'delete_journal_entries' => 'حذف القيود المحاسبية',
            'approve_journal_entries' => 'الموافقة على القيود المحاسبية',
            'post_journal_entries' => 'ترحيل القيود المحاسبية',
            'view_trial_balance' => 'عرض ميزان المراجعة',
            'view_income_statement' => 'عرض قائمة الدخل',
            'view_balance_sheet' => 'عرض الميزانية العمومية',
            'view_cash_flow' => 'عرض قائمة التدفق النقدي',
            'view_cost_centers' => 'عرض مراكز التكلفة',
            'create_cost_centers' => 'إنشاء مراكز التكلفة',
            'edit_cost_centers' => 'تعديل مراكز التكلفة',
            'delete_cost_centers' => 'حذف مراكز التكلفة',
            'view_financial_reports' => 'عرض التقارير المالية',
            'export_financial_reports' => 'تصدير التقارير المالية',
            'close_accounting_period' => 'إقفال الفترة المحاسبية',
            
            // ===== الموارد البشرية =====
            'view_hr_dashboard' => 'عرض لوحة تحكم الموارد البشرية',
            'view_employees' => 'عرض الموظفين',
            'create_employees' => 'إضافة موظفين',
            'edit_employees' => 'تعديل الموظفين',
            'delete_employees' => 'حذف الموظفين',
            'view_employee_files' => 'عرض ملفات الموظفين',
            'manage_employee_documents' => 'إدارة وثائق الموظفين',
            'view_departments' => 'عرض الأقسام',
            'create_departments' => 'إنشاء أقسام',
            'edit_departments' => 'تعديل الأقسام',
            'delete_departments' => 'حذف الأقسام',
            'view_positions' => 'عرض المناصب',
            'create_positions' => 'إنشاء مناصب',
            'edit_positions' => 'تعديل المناصب',
            'delete_positions' => 'حذف المناصب',
            'view_attendance' => 'عرض الحضور والانصراف',
            'record_attendance' => 'تسجيل الحضور والانصراف',
            'edit_attendance' => 'تعديل الحضور والانصراف',
            'view_leave_requests' => 'عرض طلبات الإجازات',
            'create_leave_requests' => 'إنشاء طلبات الإجازات',
            'approve_leave_requests' => 'الموافقة على طلبات الإجازات',
            'reject_leave_requests' => 'رفض طلبات الإجازات',
            'view_payroll' => 'عرض كشف الرواتب',
            'process_payroll' => 'معالجة كشف الرواتب',
            'approve_payroll' => 'الموافقة على كشف الرواتب',
            'view_hr_reports' => 'عرض تقارير الموارد البشرية',
            'export_hr_reports' => 'تصدير تقارير الموارد البشرية',
            
            // ===== إدارة المشتريات =====
            'view_purchasing_dashboard' => 'عرض لوحة تحكم المشتريات',
            'view_suppliers' => 'عرض الموردين',
            'create_suppliers' => 'إضافة موردين',
            'edit_suppliers' => 'تعديل الموردين',
            'delete_suppliers' => 'حذف الموردين',
            'view_supplier_evaluations' => 'عرض تقييمات الموردين',
            'create_supplier_evaluations' => 'إنشاء تقييمات الموردين',
            'view_purchase_requests' => 'عرض طلبات الشراء',
            'create_purchase_requests' => 'إنشاء طلبات الشراء',
            'edit_purchase_requests' => 'تعديل طلبات الشراء',
            'approve_purchase_requests' => 'الموافقة على طلبات الشراء',
            'reject_purchase_requests' => 'رفض طلبات الشراء',
            'view_purchase_orders' => 'عرض أوامر الشراء',
            'create_purchase_orders' => 'إنشاء أوامر الشراء',
            'edit_purchase_orders' => 'تعديل أوامر الشراء',
            'approve_purchase_orders' => 'الموافقة على أوامر الشراء',
            'cancel_purchase_orders' => 'إلغاء أوامر الشراء',
            'view_quotations' => 'عرض عروض الأسعار',
            'create_quotations' => 'إنشاء عروض الأسعار',
            'compare_quotations' => 'مقارنة عروض الأسعار',
            'view_goods_receipt' => 'عرض استلام البضائع',
            'create_goods_receipt' => 'إنشاء استلام البضائع',
            'view_purchasing_reports' => 'عرض تقارير المشتريات',
            'export_purchasing_reports' => 'تصدير تقارير المشتريات',
            
            // ===== الشؤون التنظيمية =====
            'view_regulatory_dashboard' => 'عرض لوحة تحكم الشؤون التنظيمية',
            'view_company_registrations' => 'عرض تسجيلات الشركات',
            'create_company_registrations' => 'إنشاء تسجيلات الشركات',
            'edit_company_registrations' => 'تعديل تسجيلات الشركات',
            'view_product_registrations' => 'عرض تسجيلات المنتجات',
            'create_product_registrations' => 'إنشاء تسجيلات المنتجات',
            'edit_product_registrations' => 'تعديل تسجيلات المنتجات',
            'view_quality_certificates' => 'عرض شهادات الجودة',
            'create_quality_certificates' => 'إنشاء شهادات الجودة',
            'edit_quality_certificates' => 'تعديل شهادات الجودة',
            'renew_quality_certificates' => 'تجديد شهادات الجودة',
            'view_inspections' => 'عرض التفتيش التنظيمي',
            'schedule_inspections' => 'جدولة التفتيش التنظيمي',
            'conduct_inspections' => 'إجراء التفتيش التنظيمي',
            'view_regulatory_reports' => 'عرض التقارير التنظيمية',
            'create_regulatory_reports' => 'إنشاء التقارير التنظيمية',
            'submit_regulatory_reports' => 'تقديم التقارير التنظيمية',
            'view_product_recalls' => 'عرض سحب المنتجات',
            'initiate_product_recalls' => 'بدء سحب المنتجات',
            'manage_product_recalls' => 'إدارة سحب المنتجات',
            
            // ===== الذكاء الاصطناعي والتحليلات =====
            'view_analytics_dashboard' => 'عرض لوحة تحكم التحليلات',
            'view_sales_analytics' => 'عرض تحليلات المبيعات',
            'view_inventory_analytics' => 'عرض تحليلات المخزون',
            'view_financial_analytics' => 'عرض التحليلات المالية',
            'view_customer_analytics' => 'عرض تحليلات العملاء',
            'view_market_trends' => 'عرض اتجاهات السوق',
            'view_predictive_analytics' => 'عرض التحليلات التنبؤية',
            'generate_ai_insights' => 'توليد رؤى الذكاء الاصطناعي',
            'view_performance_kpis' => 'عرض مؤشرات الأداء الرئيسية',
            'create_custom_reports' => 'إنشاء تقارير مخصصة',
            'schedule_reports' => 'جدولة التقارير',
            'export_analytics_data' => 'تصدير بيانات التحليلات',
            
            // ===== دليل النظام =====
            'view_system_guide' => 'عرض دليل النظام',
            'view_video_tutorials' => 'عرض الفيديوهات التعليمية',
            'view_faq' => 'عرض الأسئلة الشائعة',
            'download_user_manual' => 'تحميل دليل المستخدم',
            'access_interactive_tours' => 'الوصول للجولات التفاعلية',
            'view_module_guides' => 'عرض أدلة الوحدات',
            'create_support_tickets' => 'إنشاء تذاكر الدعم',
            'view_support_tickets' => 'عرض تذاكر الدعم',
            
            // ===== التقارير العامة =====
            'view_all_reports' => 'عرض جميع التقارير',
            'create_custom_reports' => 'إنشاء تقارير مخصصة',
            'schedule_reports' => 'جدولة التقارير',
            'export_reports' => 'تصدير التقارير',
            'share_reports' => 'مشاركة التقارير',
            'print_reports' => 'طباعة التقارير',
        ];

        foreach ($permissions as $name => $description) {
            Permission::firstOrCreate(
                ['name' => $name],
                ['description' => $description]
            );
        }
        
        $this->command->info('تم إنشاء ' . count($permissions) . ' صلاحية بنجاح!');
    }
}
